[package]
name = "game"
version = "0.0.1"
authors = ["Fedcomp"]
edition = "2018"

[dependencies]
bevy = "0.2.1"
bevy_rapier2d = "0.3.1"
log = "0.4.11"
env_logger = "0.7.1"
tiled = "0.9.3"
anyhow = "1.0.33"


