[package]
name = "bundlebox"
description = "Zombie Redemption asset optimizer/bundler"
version = "0.0.1"
authors = ["Fedcomp"]
edition = "2018"

[dependencies]
clap = "2.33.3"
anyhow = "1.0.33"
log = "0.4.11"
env_logger = "0.8.1"
walkdir = "2.3.1"
